# Generated by Django 2.0 on 2017-12-23 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlıq')),
                ('content', models.TextField(default='', max_length=250, verbose_name='Mətn')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-publish_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('user_name', models.CharField(max_length=20, verbose_name='surname')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
            ],
        ),
    ]
