# Generated by Django 2.0 on 2017-12-24 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_auto_20171223_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Mətn'),
        ),
    ]
